// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chuzgwilzttxytcltmvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNodXpnd2lsenR0eHl0Y2x0bXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTQ5MTgsImV4cCI6MjA3NTY3MDkxOH0.r3TrVTWc22LjftcqvgMbUC4vCHiXmRxhE-krgr0-81E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});